In [1]:
from insight import *
from insight_tools import *

In [9]:
# filepath = '/Users/shinan/Downloads/VI-Core/visual-insights-lab/ds-cars-service.json'
# filepath = '/Users/shinan/Downloads/VI-Core/visual-insights-lab/ds-students-service.json'
# filepath = '/Users/shinan/Downloads/VI-Core/visual-insights-lab/input_data.json'
# filepath = '/Users/shinan/Downloads/VI-Core/datasets/HumanResourcesDataSet.json'
# filepath = '/Users/shinan/Downloads/VI-Core/datasets/COVID-19-Coronavirus.json'
# filepath = '/Users/shinan/Downloads/VI-Core/datasets/Inc-5000-Companies.json'
# filepath = '/Users/shinan/Downloads/dataset-service.json'
filepath = '/Users/shinan/Downloads/test.json'
dataSource,fields = read_json(filepath)

In [3]:
traverse_return = traverse_fields(dataSource,fields)
# traverse_fields(dataSource,fields,check_list = ['2DClustering','SimpsonParadoxV2','SimpsonParadoxV1','SimpsonParadoxV3'])

In [4]:
# col = ['Acceleration', 'Weight_in_lbs', 'Year', 'Origin']
# insight_dict = insight_check(fields,dataSource.loc[:,col],check_list = ['2DClustering','SimpsonParadoxV2','SimpsonParadoxV1','SimpsonParadoxV3'])
# display_insight_dict(insight_dict,dataSource)

In [5]:
# insight_dict = insight_check(fields,dataSource)

In [6]:
traverse_return = [traverse_return[i] for i in np.argsort(-np.array([i['dict']['score'] for i in traverse_return]))]

In [7]:
# for i in traverse_return:
#     print([fields['name'][fields['fid']==j].values[0] for j in i['col']])
#     print('dimensions:',[fields['name'][fields['fid']==j].values[0] for j in i['insight_input']['dimensions']])
#     print('measures:',[fields['name'][fields['fid']==j].values[0] for j in i['insight_input']['measures']])
#     print('breakdown:',[fields['name'][fields['fid']==j].values[0] for j in i['insight_input']['breakdown']])
#     print('explain:',i['dict']['para']['explain'])
#     display_insight_dict({i['type']:i['dict']},dataSource)

In [ ]:
for i in traverse_return:
    print('explain:',i['dict']['para']['explain'])
    display_insight_dict({i['type']:i['dict']},dataSource)

In [10]:
dataSource

,col_0_53,col_1_57,col_2_83,col_3_22,col_9_13,col_10_43,col_11_91,col_13_78
0,SOGZB05371,25/11/2016,Qy1TSDA1ICA=,MDQwICAgICA=,B152935-001,45.0,10,450.0
1,SOAE008441,22/03/2018,Qy1EVDAyICA=,MDI5ICAgICA=,J141-46708,4.0,100,400.0
2,SOAB006023,09/09/2016,Qy1QWjAxICA=,MDE4ICAgICA=,NPE20,25.0,10,250.0
3,SOAF009645,30/08/2018,Qy1YTDM2ICA=,MDE3ICAgICA=,PHM1A,122.0,3,366.0
4,SOK0002632,06/09/2016,S0wwNiAgICA=,MDI1ICAgICA=,B814CF2M,187.0,25,4675.0
...,...,...,...,...,...,...,...,...
495,SOAB005056,13/08/2016,Q1MwOCAgICA=,MDI1ICAgICA=,L68124,400.0,1,400.0
496,SOAE008546,23/03/2018,Q0ctQ0gxMiA=,MDE3ICAgICA=,QBW,140.0,10,1400.0
497,SOAA009532,04/03/2016,Q0ctS0wwMyA=,MDE3ICAgICA=,J226-18060,600.0,5,3000.0
498,SOAH005395,26/01/2019,Q0ctVEgxMSA=,MDE3ICAgICA=,E580C1-81,165.0,5,825.0
499,SOAF001786,23/05/2018,Qy1LSzA1ICA=,MDQwICAgICA=,FFA1030Q,230.0,3,690.0

In [11]:
fields

,fid,geoRole,features,semanticType,analyticType,distribution,disable,name
0,col_3_22,none,"{'maxEntropy': 3.584962500721156, 'entropy': 2...",nominal,dimension,"[{'memberName': 'MDQwICAgICA=', 'count': 86}, ...",False,f_scode
1,col_9_13,none,"{'maxEntropy': 8.74819284958946, 'entropy': 8....",nominal,dimension,"[{'memberName': 'B152935-001', 'count': 1}, {'...",False,f_icode
2,col_10_43,none,"{'maxEntropy': 4, 'entropy': 3.042962327268187...",quantitative,measure,"[{'memberName': 45, 'count': 8}, {'memberName'...",False,f_uprice
3,col_13_78,none,"{'maxEntropy': 4, 'entropy': 2.030953034485129...",quantitative,measure,"[{'memberName': 450, 'count': 9}, {'memberName...",False,f_iamt

In [ ]:
if 'name' in fields.columns:
    dataSource.columns = list([fields.loc[fields['fid']==i,'name'].values[0] for i in dataSource.columns])
    dimensions = [i for i in dataSource.columns if fields[fields['name']==i]['analyticType'].values=='dimension']
    measures = [i for i in dataSource.columns if fields[fields['name']==i]['analyticType'].values=='measure']
else:
    dimensions = [i for i in dataSource.columns if fields[fields['fid']==i]['analyticType'].values=='dimension']
    measures = [i for i in dataSource.columns if fields[fields['fid']==i]['analyticType'].values=='measure']

In [20]:
import statsmodels.formula.api as sm

In [23]:
m1 = sm.glm("col_10_43 ~ col_11_91 + col_13_78", data=dataSource)

In [5]:
from clickhouse_driver import connect

In [20]:
host = '44.208.84.235'
user = 'default'
pw = '123456'
database = 'database'
conn = connect(f'clickhouse://{user}:{pw}@{host}:9000/{database}')
cursor = conn.cursor()
sql = "select fields from database.tableName"
res = cursor.execute(sql)

Error on socket shutdown: [Errno 57] Socket is not connected

OperationalError: Code: 81.
DB::Exception: Database database doesn't exist. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xaebed1a in /usr/bin/clickhouse
1. DB::DatabaseCatalog::assertDatabaseExistsUnlocked(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x146fb31a in /usr/bin/clickhouse
2. DB::DatabaseCatalog::assertDatabaseExists(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0x146fb194 in /usr/bin/clickhouse
3. DB::Context::setCurrentDatabase(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x14671bfd in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x159f10fe in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x15a03419 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x18667a0f in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x18669e61 in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x1881a549 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x18817c40 in /usr/bin/clickhouse
10. start_thread @ 0x744b in /usr/lib64/libpthread-2.26.so
11. clone @ 0xef56f in /usr/lib64/libc-2.26.so